### ISSUE TITLE
网页数据传输到后端的问题

### ISSUE THREAD

**Issue by 156466902** [LIFICN/Taro-Dev#2]
亲，再请教个问题。
我想在网页上的一个按钮点击的时候用javascript想cs后台代码传送一些页面上的数据过来 用什么方法呢？
我试过
window.chrome.webview.postMessage(window.document.URL);
但是它只能在页面加载的时候生效。按钮触发的时候会提示postMessage未定义。

谢谢

**Comment by 156466902** [comment]
我好想找到方法了。是这个吗？
CoreWebView2.AddHostObjectToScript(string, object)

**Comment by 156466902** [comment]
改成这样就可以了
window.top.chrome.webview.postMessage(datas);

**Comment by LIFICN** [comment]
window对象也是有作用域的，window.chrome.webview.postMessage这个在顶级窗口才有作用，所以window.top.chrome.webview.postMessage

**Comment by 156466902** [comment]
我让它启动后直接全屏，竟然会报错

“System.Reflection.TargetInvocationException”类型的未经处理的异常在 mscorlib.dll 中发生 

其他信息: 调用的目标发生了异常。

**Comment by LIFICN** [comment]
没看懂

**Comment by 156466902** [comment]
我的意思是，我让程序主窗体一启动就全屏显示,结果他会报错,在你这个项目里面程序一启动并没有全屏显示。

“System.Reflection.TargetInvocationException”类型的未经处理的异常在 mscorlib.dll 中发生

其他信息: 调用的目标发生了异常。
